# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppICM <- function(d, s, unit) {
    .Call(`_itmsa_RcppICM`, d, s, unit)
}

RcppICMP <- function(d, s, unit, seed, permutation_number) {
    .Call(`_itmsa_RcppICMP`, d, s, unit, seed, permutation_number)
}

RcppVMBase <- function(d, s, unit) {
    .Call(`_itmsa_RcppVMBase`, d, s, unit)
}

RcppVM <- function(d, s, unit, beta = 1) {
    .Call(`_itmsa_RcppVM`, d, s, unit, beta)
}

RcppVMP <- function(d, s, unit, beta, seed, permutation_number) {
    .Call(`_itmsa_RcppVMP`, d, s, unit, beta, seed, permutation_number)
}

